services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: page
    ports:
      - 3240:3000
    volumes:
      - ./page/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - ./portainer/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - 8090:80
    restart: unless-stopped
    volumes:
      - ./vaultwarden/vw-data/:/data/

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  samba:
    image: dockurr/samba
    container_name: samba
    ports:
      - 445:445
    volumes:
      - ./samba/public:/public
      - ./samba/storage:/storage
      - ./samba/smb.conf:/etc/samba/smb.conf
      - ./samba/users.conf:/etc/samba/users.conf

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID = 1000
      - PGUI = 1000
      - TZ = Etc/UTC
      - WEBUI_PORT = 8080
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - JELLYFIN_PublishedServerUrl=htpp://localhost/8096
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/tvshows:/data/tvshows
      - ./jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional

  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    ports:
      - 8085:80
    restart: unless-stopped
