---
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirlingpdf
    ports:
      - 8070:8080
    volumes:
      - ./stirling-data/trainingData:/usr/share/tessdata
      - ./stirling-data/extraConfigs:/configs
      - ./stirling-data/customFiles:/customFiles/
      - ./stirling-data/logs:/logs/
      - ./stirling-data/pipeline:/pipeline/
    networks:
      - homelab-network
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB

networks:
  homelab-network:
    external: true
