---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: Brook's Dashboard

background: https://images.unsplash.com/photo-1475257026007-0753d5429e10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80
# background: https://images.unsplash.com/photo-1693701598372-13486b3824fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80
# background: https://images.unsplash.com/photo-1477346611705-65d1883cee1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

# providers:
  # openweathermap: openweathermapapikey
  # weatherapi: $WEATHERAPIKEY 
