---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hour12: true

- openmeteo:
    label: Addis Abeba # optional
    latitude: 45.822231
    longitude: 8.437710
    timezone: Africa/Nairobi # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
