services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    ports:
      - 3020:3000
    environment:
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234 # will use randomUUID() if unset
      # - HTTP_ALLOWED=true # uncomment this if accessing it over a non-https connection
      - ACCOUNT_REGISTRATION=false
      - ALLOW_UNAUTHENTICATED=true
    volumes:
      - ./data:/app/data
    networks:
      - homelab-network
    restart: unless-stopped

networks:
  homelab-network:
    external: true
