---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    ports:
      - 51821:51821/tcp
      - 51820:51820/udp
    volumes:
      - ./wg-easy:/etc/wireguard
    networks:
      - homelab-network
    environment:
      - LANG=en
      - WG_PORT=51820
      - WG_HOST=localhost
      - PORT=51821
      - PASSWORD_HASH=$$2a$$10$$mBSmcQbmRztw0fzgyNaMx.s5Mhc32mL43rHUIyn.VJP42Y5pFWQdi
    restart: unless-stopped

networks:
  homelab-network:
    external: true
